In [2]:
import numpy as np


#1
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array:", array1d)

#2
array2d_zeros = np.zeros((3, 3))
print("2D Array with Zeros:\n", array2d_zeros)

#3
array5x5_random = np.random.randint(1, 11, size=(5, 5))
print("5x5 Array with Random Integers:\n", array5x5_random)

#4
array4x4_random_float = np.random.rand(4, 4)
print("4x4 Array with Random Floats:\n", array4x4_random_float)

#5
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("Array 1:", array1)
print("Array 2:", array2)
print("Sum:", array1 + array2)
print("Difference:", array1 - array2)
print("Product:", array1 * array2)

#6
vector1 = np.random.randn(7)
vector2 = np.random.randn(7)
scalar_product = np.dot(vector1, vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Scalar Product:", scalar_product)

#7
matrix2x2 = np.random.randint(1, 11, size=(2, 2))
matrix2x3 = np.random.randint(1, 11, size=(2, 3))
result_matrix = np.dot(matrix2x2, matrix2x3)
print("Matrix 2x2:\n", matrix2x2)
print("Matrix 2x3:\n", matrix2x3)
print("Result Matrix:\n", result_matrix)

#8
matrix3x3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix3x3)
print("Matrix 3x3:\n", matrix3x3)
print("Inverse Matrix:\n", inverse_matrix)

#9
matrix4x4_transposed = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix4x4_transposed)
print("Original Matrix 4x4:\n", matrix4x4_transposed)
print("Transposed Matrix 4x4:\n", transposed_matrix)

#10
matrix3x4 = np.random.randint(1, 11, size=(3, 4))
vector4 = np.random.randint(1, 11, size=4)
result_vector = np.dot(matrix3x4, vector4)
print("Matrix 3x4:\n", matrix3x4)
print("Vector 4:\n", vector4)
print("Result Vector:\n", result_vector)

#11
matrix2x3 = np.random.rand(2, 3)
vector3 = np.random.rand(3)
result_vector = np.dot(matrix2x3, vector3)
print("Matrix 2x3:\n", matrix2x3)
print("Vector 3:\n", vector3)
print("Result Vector:\n", result_vector)

#12
matrix2x2_elementwise = np.random.randint(1, 11, size=(2, 2))
matrix2x2_product = np.multiply(matrix2x2_elementwise, matrix2x2_elementwise)
print("Matrix 2x2 (Elementwise):\n", matrix2x2_elementwise)
print("Matrix 2x2 (Product):\n", matrix2x2_product)

#13
matrix2x2_1 = np.random.randint(1, 11, size=(2, 2))
matrix2x2_2 = np.random.randint(1, 11, size=(2, 2))
matrix2x2_product = np.dot(matrix2x2_1, matrix2x2_2)
print("Matrix 1 (2x2):\n", matrix2x2_1)
print("Matrix 2 (2x2):\n", matrix2x2_2)
print("Matrix Product (2x2):\n", matrix2x2_product)

#14
matrix5x5_sum = np.random.randint(1, 101, size=(5, 5))
sum_of_elements = np.sum(matrix5x5_sum)
print("Matrix 5x5:\n", matrix5x5_sum)
print("Sum of Elements:", sum_of_elements)

#15
matrix4x4_1 = np.random.randint(1, 11, size=(4, 4))
matrix4x4_2 = np.random.randint(1, 11, size=(4, 4))
matrix4x4_difference = matrix4x4_1 - matrix4x4_2
print("Matrix 1 (4x4):\n", matrix4x4_1)
print("Matrix 2 (4x4):\n", matrix4x4_2)
print("Matrix Difference (4x4):\n", matrix4x4_difference)

#16
matrix3x3_random = np.random.rand(3, 3)
row_sums = np.sum(matrix3x3_random, axis=1)
column_vector = row_sums.reshape((3, 1))
print("Matrix 3x3 (Random):\n", matrix3x3_random)
print("Column Vector (Row Sums):\n", column_vector)

#17
matrix3x4_squared = np.random.randint(1, 11, size=(3, 4))
matrix_squared = np.square(matrix3x4_squared)
print("Original Matrix 3x4:\n", matrix3x4_squared)
print("Squared Matrix 3x4:\n", matrix_squared)

#18
vector4_sqrt = np.random.randint(1, 51, size=4)
vector_sqrt = np.sqrt(vector4_sqrt)
print("Original Vector 4:\n", vector4_sqrt)
print("Vector with Square Roots:\n", vector_sqrt)



1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array with Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
5x5 Array with Random Integers:
 [[ 5  5  5  1  2]
 [ 2  2  2  4  4]
 [ 7 10  2  5  4]
 [ 9  8  2  6 10]
 [ 2  8 10  9  4]]
4x4 Array with Random Floats:
 [[0.45816625 0.54325322 0.84209163 0.18147431]
 [0.57240573 0.09757543 0.18444477 0.53430331]
 [0.65163663 0.44163956 0.77283689 0.87177357]
 [0.13608893 0.15070079 0.50115281 0.41539371]]
Array 1: [10  4  2  5  6]
Array 2: [6 6 5 5 8]
Sum: [16 10  7 10 14]
Difference: [ 4 -2 -3  0 -2]
Product: [60 24 10 25 48]
Vector 1: [-0.41354509  1.35773682 -1.34814258  0.43299931  0.23768448  1.58327034
 -1.08956094]
Vector 2: [ 1.05298828  1.11189961  0.55192334  0.02028364  1.10499982 -1.06444534
 -0.56580715]
Scalar Product: -0.4672616990402722
Matrix 2x2:
 [[ 3 10]
 [10  6]]
Matrix 2x3:
 [[10  5  4]
 [ 2  9  2]]
Result Matrix:
 [[ 50 105  32]
 [112 104  52]]
Matrix 3x3:
 [[1 1 7]
 [4 9 1]
 [8 5 2]]
Inverse Matrix:
 [[-0.03703704 -0.09401709 