In [1]:
import numpy as np
#1
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array:", array1d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]


In [2]:
#2
array2d_zeros = np.zeros((3, 3))
print("2D Array with Zeros:\n", array2d_zeros)

2D Array with Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#3
array5x5_random = np.random.randint(1, 11, size=(5, 5))
print("5x5 Array with Random Integers:\n", array5x5_random)

5x5 Array with Random Integers:
 [[3 6 8 4 3]
 [6 4 6 3 2]
 [5 7 2 7 3]
 [4 9 9 8 9]
 [5 1 4 1 3]]


In [4]:
#4
array4x4_random_float = np.random.rand(4, 4)
print("4x4 Array with Random Floats:\n", array4x4_random_float)

4x4 Array with Random Floats:
 [[0.23363194 0.54984117 0.21183517 0.39808538]
 [0.6498077  0.44093712 0.34858732 0.82259276]
 [0.96791155 0.93301749 0.02351835 0.17374288]
 [0.21810836 0.32990578 0.5164329  0.47242286]]


In [5]:
#5
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print("Array 1:", array1)
print("Array 2:", array2)
print("Sum:", array1 + array2)
print("Difference:", array1 - array2)
print("Product:", array1 * array2)

Array 1: [1 8 3 4 4]
Array 2: [10  5 10 10 10]
Sum: [11 13 13 14 14]
Difference: [-9  3 -7 -6 -6]
Product: [10 40 30 40 40]


In [6]:
#6
vector1 = np.random.randn(7)
vector2 = np.random.randn(7)
scalar_product = np.dot(vector1, vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Scalar Product:", scalar_product)

Vector 1: [-1.10643038 -0.26689143 -0.21094751 -0.26336239  1.47726253 -0.74506085
 -0.91829393]
Vector 2: [-0.411287    1.00879288 -0.31081605  1.01245247 -1.63433352  0.85310922
  0.75140408]
Scalar Product: -3.755221525005624


In [7]:
#7
matrix2x2 = np.random.randint(1, 11, size=(2, 2))
matrix2x3 = np.random.randint(1, 11, size=(2, 3))
result_matrix = np.dot(matrix2x2, matrix2x3)
print("Matrix 2x2:\n", matrix2x2)
print("Matrix 2x3:\n", matrix2x3)
print("Result Matrix:\n", result_matrix)

Matrix 2x2:
 [[3 5]
 [5 5]]
Matrix 2x3:
 [[ 8 10  1]
 [ 8  3  8]]
Result Matrix:
 [[64 45 43]
 [80 65 45]]


In [8]:
#8
matrix3x3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix3x3)
print("Matrix 3x3:\n", matrix3x3)
print("Inverse Matrix:\n", inverse_matrix)

Matrix 3x3:
 [[4 4 5]
 [6 4 6]
 [7 9 4]]
Inverse Matrix:
 [[-0.76  0.58  0.08]
 [ 0.36 -0.38  0.12]
 [ 0.52 -0.16 -0.16]]


In [9]:
#9
matrix4x4_transposed = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix4x4_transposed)
print("Original Matrix 4x4:\n", matrix4x4_transposed)
print("Transposed Matrix 4x4:\n", transposed_matrix)

Original Matrix 4x4:
 [[0.23250435 0.01686451 0.49969402 0.15892777]
 [0.8936606  0.14558085 0.78884774 0.66516901]
 [0.00994494 0.06928345 0.55740965 0.36860387]
 [0.99342025 0.36122159 0.24662509 0.73705284]]
Transposed Matrix 4x4:
 [[0.23250435 0.8936606  0.00994494 0.99342025]
 [0.01686451 0.14558085 0.06928345 0.36122159]
 [0.49969402 0.78884774 0.55740965 0.24662509]
 [0.15892777 0.66516901 0.36860387 0.73705284]]


In [10]:
#10
matrix3x4 = np.random.randint(1, 11, size=(3, 4))
vector4 = np.random.randint(1, 11, size=4)
result_vector = np.dot(matrix3x4, vector4)
print("Matrix 3x4:\n", matrix3x4)
print("Vector 4:\n", vector4)
print("Result Vector:\n", result_vector)

Matrix 3x4:
 [[ 4  7  6  9]
 [ 4  8  1  8]
 [ 5  8  7 10]]
Vector 4:
 [ 8  4 10  1]
Result Vector:
 [129  82 152]


In [11]:
#11
matrix2x3 = np.random.rand(2, 3)
vector3 = np.random.rand(3)
result_vector = np.dot(matrix2x3, vector3)
print("Matrix 2x3:\n", matrix2x3)
print("Vector 3:\n", vector3)
print("Result Vector:\n", result_vector)

Matrix 2x3:
 [[0.87694051 0.98963764 0.31458222]
 [0.64098111 0.30460455 0.17138214]]
Vector 3:
 [0.07562725 0.02162975 0.11380545]
Result Vector:
 [0.12352739 0.07456838]


In [12]:
#12
matrix2x2_elementwise = np.random.randint(1, 11, size=(2, 2))
matrix2x2_product = np.multiply(matrix2x2_elementwise, matrix2x2_elementwise)
print("Matrix 2x2 (Elementwise):\n", matrix2x2_elementwise)
print("Matrix 2x2 (Product):\n", matrix2x2_product)

Matrix 2x2 (Elementwise):
 [[6 9]
 [4 4]]
Matrix 2x2 (Product):
 [[36 81]
 [16 16]]


In [13]:
#13
matrix2x2_1 = np.random.randint(1, 11, size=(2, 2))
matrix2x2_2 = np.random.randint(1, 11, size=(2, 2))
matrix2x2_product = np.dot(matrix2x2_1, matrix2x2_2)
print("Matrix 1 (2x2):\n", matrix2x2_1)
print("Matrix 2 (2x2):\n", matrix2x2_2)
print("Matrix Product (2x2):\n", matrix2x2_product)

Matrix 1 (2x2):
 [[7 6]
 [8 2]]
Matrix 2 (2x2):
 [[9 2]
 [3 9]]
Matrix Product (2x2):
 [[81 68]
 [78 34]]


In [14]:
#14
matrix5x5_sum = np.random.randint(1, 101, size=(5, 5))
sum_of_elements = np.sum(matrix5x5_sum)
print("Matrix 5x5:\n", matrix5x5_sum)
print("Sum of Elements:", sum_of_elements)

Matrix 5x5:
 [[ 49  95  35  12  58]
 [ 59  40  49  26  44]
 [ 22  61  67  27  11]
 [ 57  67  60 100  70]
 [ 63  75  57   9  27]]
Sum of Elements: 1240


In [15]:
#15
matrix4x4_1 = np.random.randint(1, 11, size=(4, 4))
matrix4x4_2 = np.random.randint(1, 11, size=(4, 4))
matrix4x4_difference = matrix4x4_1 - matrix4x4_2
print("Matrix 1 (4x4):\n", matrix4x4_1)
print("Matrix 2 (4x4):\n", matrix4x4_2)
print("Matrix Difference (4x4):\n", matrix4x4_difference)

Matrix 1 (4x4):
 [[ 2  5 10  9]
 [ 1 10  6  5]
 [ 5  5  9  4]
 [ 5  3  2  2]]
Matrix 2 (4x4):
 [[6 9 3 5]
 [1 5 1 4]
 [9 8 3 8]
 [2 4 3 7]]
Matrix Difference (4x4):
 [[-4 -4  7  4]
 [ 0  5  5  1]
 [-4 -3  6 -4]
 [ 3 -1 -1 -5]]


In [16]:
#16
matrix3x3_random = np.random.rand(3, 3)
row_sums = np.sum(matrix3x3_random, axis=1)
column_vector = row_sums.reshape((3, 1))
print("Matrix 3x3 (Random):\n", matrix3x3_random)
print("Column Vector (Row Sums):\n", column_vector)

Matrix 3x3 (Random):
 [[0.70496619 0.89689292 0.86157234]
 [0.09347465 0.17792215 0.97935815]
 [0.6460543  0.5543121  0.85077718]]
Column Vector (Row Sums):
 [[2.46343145]
 [1.25075494]
 [2.05114359]]


In [17]:
#17
matrix3x4_squared = np.random.randint(1, 11, size=(3, 4))
matrix_squared = np.square(matrix3x4_squared)
print("Original Matrix 3x4:\n", matrix3x4_squared)
print("Squared Matrix 3x4:\n", matrix_squared)

Original Matrix 3x4:
 [[ 2 10  6  5]
 [ 8  4  3 10]
 [ 8  8  8 10]]
Squared Matrix 3x4:
 [[  4 100  36  25]
 [ 64  16   9 100]
 [ 64  64  64 100]]


In [18]:
#18
vector4_sqrt = np.random.randint(1, 51, size=4)
vector_sqrt = np.sqrt(vector4_sqrt)
print("Original Vector 4:\n", vector4_sqrt)
print("Vector with Square Roots:\n", vector_sqrt)

Original Vector 4:
 [29 11 18 24]
Vector with Square Roots:
 [5.38516481 3.31662479 4.24264069 4.89897949]
